### PR TITLE
Updated the ft_plugins screenshot to be more up-to-date and high resolution.

### PR DESCRIPTION
**Pull request by KamranMackey**
The image kind of needed an update.

### CODE REVIEW

**Comment by flashcode** [comment]
Hi,
Thanks for the new image, but the small size was a choice: it displays fine on small screens (like netbooks or smartphones).
And if we resize this one (your pull request), we should resize all other images on the same page.
I think for now even if it's small, it displays fine with text beside.

**Comment by KamranMackey** [comment]
@flashcode you could just update the HTML to reflect the same size that the other image was, by using the `<height>` and `<width>` HTML tags.

**Comment by KamranMackey** [comment]
So in this case, all you would have to do is add `height="403" weight="253"` to the `Plugins` line.

**Comment by flashcode** [comment]
Then what's the benefit of having a larger image if I resize it to a smaller size? It's even worst: the browser will resize and the text will become unreadable.
That's why I chose a small size with no resize on display.
For larger images on what WeeChat can do, there's the screenshot page.

**Pull request closed without merging**
